defmodule Bug.BugTest do
  use Bug.DataCase

  alias Bug.Repo
  alias Bug.PrimaryModule

  test "With autogenerated id" do
    title = generate_title
    entity = %PrimaryModule{title: title} |> Repo.insert!()
    new = Repo.get!(PrimaryModule, entity.id)

    assert entity.title == title
    assert new.title == title
    assert new.id == entity.id
  end

  test "With pregenerated id" do
    title = generate_title
    id = Ecto.UUID.generate()
    entity = %PrimaryModule{id: id, title: title} |> Repo.insert!()
    new = Repo.get!(PrimaryModule, id)

    assert entity.id == id
    assert entity.title == title
    assert new.title == title
    assert new.id == entity.id
  end

  defp generate_title(length \\ 20) do
    :crypto.strong_rand_bytes(length) |> Base.url_encode64 |> binary_part(0, length)
  end
end
